version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: db_postgres
    ports:
      - "5435:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - ./shared_volume:/fastapi_app/pgdata
    environment:
      - POSTGRES_DB=documents
      - POSTGRES_USER=victor
      - POSTGRES_PASSWORD=user

  rabbit:
    image: rabbitmq:3.9.13-alpine
    container_name: rabbit_app
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=12345678
      - RABBITMQ_DEFAULT_VHOST=vdata
    depends_on:
      - db
    volumes:
      - ./shared_volume:/fastapi_app/rabbit


  app:
    build:
      context: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    env_file:
      - .env
    ports:
      - 9999:8000
    depends_on:
      - db
      - rabbit
      - celery

    volumes:
      - ./shared_volume:/fastapi_app/shared_data

  celery:
    build:
      context: .
    container_name: celery_app
    command: [ "/fastapi_app/docker/celery.sh", "celery" ]
    depends_on:
      - db
      - rabbit
    env_file:
      - .env


  flower:
    build:
      context: .
    container_name: flower_app
    command: [ "/fastapi_app/docker/celery.sh", "flower" ]
    depends_on:
      - db
      - rabbit
      - celery
    ports:
      - 8888:5555
    env_file:
      - .env

