"""add column path database

Revision ID: 469d2a6505f7
Revises: 860f574e1342
Create Date: 2024-03-10 21:45:29.495546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469d2a6505f7'
down_revision: Union[str, None] = '860f574e1342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'path')
    # ### end Alembic commands ###
